### ISSUE TITLE
Clone and issue inside the same repository / dashboard

### ISSUE THREAD

**Issue by eswsalesapgcgemea** [gatewayapps/kamino#106]
Hello
Is it possible to clone issues, associated comments, labels, and epic within the same repository ?
I will use Github for my testing
I have created master scripts that I now need to duplicate toassign 1 per testers
Each master scripts has a comment per step (for easy processing of the script)  - so it's very time consuming to copy each comment 1 by 1
thanks !

**Comment by johnmurphy01** [comment]
@eswsalesapgcgemea if I understand you correctly, you want to be able to clone a Github issue to the _original_ repository from which it came. 

I do exclude the repository that is being cloned from in the list of repositories here:
https://github.com/gatewayapps/kamino/blob/master/app.js#L224-L227

I _believe_ the only reason this was done was because it didn't make sense to clone to the same repo. But I will have to run some tests to make sure this doesn't break anything.

**Comment by johnmurphy01** [comment]
@eswsalesapgcgemea this was super simple and I think the only reason I added that restriction is because it didn't make sense to me to clone to the same repo. I'll do some more testing and then version `2.8.1` will be available in the Chrome Store in a little while. Thanks and welcome to Github!

**Comment by johnmurphy01** [comment]
In `2.8.1`. Closing

**Comment by johnmurphy01** [comment]
@all-contributors please add @eswsalesapgcgemea for bug and ideas
