### ISSUE TITLE
Is it possible to narrow permission scopes for the PAT required?

### ISSUE THREAD

**Issue by fuzzyweapon** [gatewayapps/kamino#140]
Full access seems like a lot for something that clones issues between repositories.

**Comment by johnmurphy01** [comment]
@fuzzyweapon thanks for the input! Do you have a suggestion for the scope? `repo` isn't necessarily full access but it does give you read and write access to private and public repos.

**Comment by danielgary** [comment]
I can provide some insight on this.  Because this isn't a GitHub App but an OAUTH app, GitHub doesn't provide the granularity needed to only R/W issues.  

I certainly understand your concern, but it's one of the reasons the project is open source.  If you want to compile yourself and install, you can.

**Comment by fuzzyweapon** [comment]
Thanks!  Understood and makes sense!
