### ISSUE TITLE
Batch cloning for multiple issues

### ISSUE THREAD

**Issue by finger563** [gatewayapps/kamino#143]
Allowing selection of multiple issues for batch cloning

**Comment by johnmurphy01** [comment]
@finger563 thanks for the suggestion! I'd have to give some thought on how to best present this feature from a UI perspective

**Comment by mbattaglia** [comment]
Kamino cloned this issue to [mbattaglia/test-repo](https://github.com/mbattaglia/test-repo/issues/1)

**Comment by mbattaglia** [comment]
Kamino cloned this issue to [mbattaglia/DESTINO](https://github.com/mbattaglia/DESTINO/issues/1)

**Comment by johnmurphy01** [comment]
@all-contributors please add @finger563 for ideas

**Comment by safaorhan** [comment]
Hello, I am also interested in a feature for bulk copying all (or some) issues to a repository.

I create educational github repositories and create issues in them. I want my students to be able to clone the repo (github supports this already) with all issues (where kamino will be handy)

So my students can get an exact copy of the repository, work on the issues without affecting the original material in the original repo.

Thanks a lot for creating such an extension!

**Comment by johnmurphy01** [comment]
Thanks @safaorhan! I believe it could be possible to make Kamino perform bulk/batch cloning for all issues in a repo. But this would be a pretty big feature that Kamino originally wasn't meant to support. Due to my time constraints, it may be a while before I would be able to work on this. But, this being an open source project, if anyone has time and wants to tackle it I am open to a PR!

**Comment by MaksimZinovev** [comment]
Hi John! 
Thank you for this tool! This is exactly what I was looking for. I am a software tester and I am experimenting with different ways to trace requirements and comments in our GithHub repo. Looks like your tool allows me to create my own repo and import issues so that I can modify them as per my needs. 

It would be great if you could add Batch cloning or even Sync feature. Any updates on that?
Thanks
PS: I made a small donation via PayPal

**Comment by johnmurphy01** [comment]
@MaksimZinovev thanks for the donation! This has been an oft requested feature.

I've been considering how it should be best implemented and that's currently where I'm at in the process. As I've mentioned before, this isn't something that Kamino was ever meant to do. 

I would think this wouldn't really even be a part of the Kamino UI, it would possibly be on the main repo page or main issues list page with the ability to select one or more issues and a destination.

My time is still limited so this could still be a while out before it comes to fruition. And as I've always said, I'm open to a PR from someone to make this happen, I think it's a good idea!

**Comment by johnmurphy01** [comment]
Hmmm, I did a thing. Still a work in progress but it's getting there!!

![image](https://user-images.githubusercontent.com/2939548/117323733-c5908200-ae54-11eb-98dd-5b19977d4ae8.png)

**Comment by johnmurphy01** [comment]
Will be in version `3.0.0`!!!
