### ISSUE TITLE
When clicking on the Kamino link in GitHub, it opens the settings page

### ISSUE THREAD

**Issue by tibi-extera** [gatewayapps/kamino#163]
I have created a PAT with all the access options that GitHub offers, not just the repo one. I have pasted the PAT to the Kamino settings and saved. 

I opened my repository, and indeed the Kamino section appears at the top of the right bar. However, when I click on the Kamino link, a new tab opens with the Kamino settings. I do not get a list of repositories, and I am not able to clone the issue.

I am using Windows 10 enterprise build 1909 and Microsoft Edge Version 85.0.564.63 (Official build) (64-bit)

**Comment by johnmurphy01** [comment]
@tibi-extera when you say "when I click on the Kamino link", are you clicking on this?
![image](https://user-images.githubusercontent.com/2939548/94851861-a200e700-03ee-11eb-8411-0905d5538d63.png)

If so, that will take you to the options screen.

You have to click the button here: 
![image](https://user-images.githubusercontent.com/2939548/94851909-b3e28a00-03ee-11eb-9de0-3a4119daabc7.png)

In order to start cloning the issue to a repo

Let me know if this doesn't work for you

**Comment by tibi-extera** [comment]
I am now embarrassed. Yes, I clicked on the first one and that opens the settings. Did not even notice the big green button.

I have now used the Clone to button (duh!) and I can confirm that it works just fine. My issue was cloned, with all the data.

Thank you for this extension, it is a life saver and sorry for wasting your time.

**Comment by johnmurphy01** [comment]
@tibi-extera no problem at all! I am glad Kamino is helpful to you
